version: 1
workflow: "Test grader - test-example"
model: ${BEDROCK_MODEL_ID}
guardrails: ["pii-basic", "secrets-default"]

env:
  max_runtime_seconds: 900
  artifacts_dir: .bcce_runs/${RUN_ID}

steps:
  - id: discover_tests
    type: prompt
    prompt_file: prompt.md
    available_tools: [ReadFile, Search]
    inputs:
      paths: ["**/*test*", "**/test*/**"]
      file_size_limit_kb: 256

  - id: analyze_coverage  
    type: agent
    policy:
      timeout_seconds: 300
      max_files: 20
      max_edits: 1
      allowed_paths: ["**/*test*", "src/**", "lib/**"]
      cmd_allowlist: ["npm", "yarn", "pytest", "go", "mvn"]
    available_tools: [ReadFile, Search, Cmd]

  - id: run_tests
    type: cmd
    command: "npm test || pytest || go test ./... || echo 'No test runner detected'"
    on_error: continue

  - id: generate_report
    type: prompt
    prompt_file: prompt.md
    available_tools: [ReadFile]
